[workspace]
resolver = "2"
members = [
    "crates/dataplane-core",
    "crates/dataplane-file",
    "crates/dataplane-ts",
    "crates/dataplane-log",
    "crates/dataplane-kv",
    "crates/dataplane-sql",
    "crates/dataplane-adapter-postgres",
    "crates/dataplane-adapter-mysql",
    "crates/dataplane-adapter-redis",
    "crates/dataplane-adapter-elasticsearch",
    "crates/dataplane-adapter-doris",
    "crates/dataplane-adapter-influxdb",
    "crates/dataplane-adapter-victoriametrics",
    "bins/apiserver",
    "bins/dpc",
    "bins/gse-server",
    "bins/gse-agent",
    "crates/gse-proto",
    "crates/gse-server-core",
    "crates/gse-agent-core",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
dataplane-core = { path = "crates/dataplane-core" }
dataplane-file = { path = "crates/dataplane-file" }
dataplane-ts = { path = "crates/dataplane-ts" }
dataplane-log = { path = "crates/dataplane-log" }
dataplane-kv = { path = "crates/dataplane-kv" }
dataplane-sql = { path = "crates/dataplane-sql" }

gse-proto = { path = "crates/gse-proto" }
gse-server-core = { path = "crates/gse-server-core" }
gse-agent-core = { path = "crates/gse-agent-core" }

geminio = { git = "https://github.com/singchia/geminio-rs", rev = "ff4363f814398b36c6ddf37b3d9042eb0b1dd802" }

tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "thin"