[package]
name = "dataplane-log"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dataplane-core.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde_json = { workspace = true }
tantivy = "0.26"
tantivy-jieba = "0.20"
uuid = { version = "1", features = ["v4"] }