name: Helm CI

on:
  pull_request:
    paths: ['charts/**']
  push:
    branches: [main]
    paths: ['charts/**']

jobs:
  helm-ci:
    uses: abrance/yoc/.github/workflows/helm-ci.yml@main
    with:
      working-directory: charts
      run-lint: true
      run-template: true
      run-unit: true